
name: Build thesis PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    env:
      FILELIST:
        01_front_material/1_title.md
        01_front_material/2_declaration.md
        01_front_material/3_abstract.md
        01_front_material/4_acknowledgements.md
        01_front_material/5_abbreviations.md
        break_____________________
        92_toc/table_of_contents.md
        92_toc/list_of_figures.md
        92_toc/list_of_tables.md
        break_____________________
        00_chapters/chapter0_chaprtersStartHere.md
        00_chapters/chapter1_introduction.md
        00_chapters/chapter2_litReview.md
        00_chapters/chapter3_methodology.md
        00_chapters/chapter4_systemRequirements.md
        00_chapters/chapter5_systemDesign.md
        00_chapters/chapter6_results.md
        00_chapters/chapter7_conclusions.md
        00_chapters/chapter8_futureWork.md
        break_____________________
        04_appendices/0_appendices.md
        04_appendices/A_software_tools.md
        04_appendices/C_webapplication.md
        break_____________________        
        05_references/references.md
    steps:
      - uses: actions/checkout@v2
      - run: 
          mkdir output  # create output dir
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/thesis.pdf -H 91_preable/preamble.tex -V fontsize=10pt -V documentclass:book -V papersize:a4paper -V classoption:openright --number-sections --csl=harvard-limerick.csl ${{ env.FILELIST }} --bibliography=05_references/references.bib
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
